#!/bin/bash
# Set GAMEDIR to the current directory and set logfile
GAMEDIR="$PWD"
LOGFILE="$GAMEDIR/patchlog.txt"

# Redirect output and error to the log file
exec > >(tee -a "$LOGFILE") 2>&1
echo "GAMEDIR is set to: $GAMEDIR"

# Exports
export DATADIR="$GAMEDIR/assets"
export DATAFILE="digital_tamers_2.port"
export LD_LIBRARY_PATH="/usr/lib:$GAMEDIR/lib:$GAMEDIR/tools/libs:$LD_LIBRARY_PATH"
export SDL_GAMECONTROLLERCONFIG="$sdl_controllerconfig"
export TOOLDIR="$GAMEDIR/tools"
export TMPDIR="$GAMEDIR/tmp"
export PATH="$GAMEDIR/tools:$PATH"

# Permissions
chmod 666 /dev/uinput
chmod 777 "$TOOLDIR/gmKtool.py"
chmod 777 "$TOOLDIR/oggenc"

cd "$GAMEDIR"

unzip_assets() {
    # Unzip assets from the located .exe file into $DATADIR
    echo "Unzipping assets from $EXE_FILE..."
    ./tools/7za x "$EXE_FILE" -o"$DATADIR" -y
    
    if [ $? -eq 0 ]; then
        echo "Assets unzipped successfully to $DATADIR."
        rm -f "$EXE_FILE"
    else
        echo "Failed to unzip assets."
        exit 1
    fi
}

apply_xdelta() {
    # Check if both data.win and dt2.xdelta files exist before applying the patch
    if [ -f "$DATADIR/data.win" ]; then
        if [ -f "./tools/patches/dt2.xdelta" ]; then
            output=$(xdelta3 -d -s "$DATADIR/data.win" -f "./tools/patches/dt2.xdelta" "$DATADIR/game.droid" 2>&1)
            if [ $? -eq 0 ]; then
                echo "Patch applied successfully"
                echo "$output"
                rm "$DATADIR/data.win"
            else
                echo "Failed to apply patch"
                echo "$output"
                exit 1
            fi
        else
            echo "No .xdelta file found; skipping patching."
        fi
    else
        echo "No data.win file found to patch!"
    fi
}

compress_audio() {
    mkdir -p "$TMPDIR"

    # Run the compression tool
    PYTHON=$(which python3)
    if [ "$PREPATCH" != 1 ]; then
        echo "Running GMTools on data and audiogroups."
        $PYTHON ./tools/gmKtool.py -vvv -m 1000 -r -b 64 -d "$TMPDIR" "$DATADIR/game.droid"
    else
        echo "Running GMTools on data file only."
        $PYTHON ./tools/gmKtool.py -v -O 0 -m 1000 -b 64 -r -d "$TMPDIR" "$DATADIR/game.droid"
    fi

    if [ $? -eq 0 ]; then
        echo "Compression completed successfully."
        mv "$TMPDIR/"* "$DATADIR"
        echo "Moved compressed files to $DATADIR."
        rmdir "$TMPDIR"
        echo "Temporary directory $TMPDIR removed."
        echo "Audio compression applied successfully."
    else
        echo "Audio compression failed."
        echo "Cleaning up temporary directory $TMPDIR."
        rm -rf "$TMPDIR"
    fi
}

zip_archive() {
        zip -r -0 $DATAFILE ./assets/
        echo "Zipped contents to $DATAFILE"
        rm -rf ./assets
        mkdir -p saves
}

process_game() {
    # Locate the .exe file in $DATADIR
    EXE_FILE=$(find "$DATADIR" -maxdepth 1 -name "*.exe" | head -n 1)

    if [ -z "$EXE_FILE" ]; then
        echo "No .exe file found in $DATADIR."
        exit 1
    else
        unzip_assets
    fi
    
    # Unzip the xdelta
    echo "Unzipping the patch file..."
    cat "./tools/patches/dt2.zip."* > "./tools/patches/dt2.zip"
    if unzip "./tools/patches/dt2.zip"; then
        echo "Unzip successful, removing the zip file..."
        rm -rf "./tools/patches/dt2.zip"
    else
        echo "Unzip failed, exiting..."
        sleep 2
        exit 1
    fi
    
    echo "Applying xdelta patch"
    apply_xdelta
    sleep 1
    echo "Compressing audio..."
    compress_audio
    sleep 1
    echo "Finishing up..."
    zip_archive
    sleep 1
	
    # Final completion message
    echo "Patching process complete!"
}

# Call the function
process_game